=== FlorentMouysset/IAWSProjet/Covoiturage-Spring-WS/Covoiturage-WS/src/main/webapp/WEB-INF/xsd/Covoiturage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:exem="http://www.univ-tlse3.fr/Services/Covoiturage"
	attributeFormDefault="unqualified" elementFormDefault="qualified"
	targetNamespace="http://www.univ-tlse3.fr/Services/Covoiturage">


	<!-- ************************** REPONSE ************************** -->
	<!-- _______ Operation Ajoute personne _______ -->
	<xs:element name="Ajout" type="exem:AjoutPersonneType"
		xmlns:exem="http://www.univ-tlse3.fr/Services/Covoiturage" />

	<!-- retour de la méthode 'Ajout' : type complexe 'AjoutPersonne' -->
	<xs:complexType name="AjoutPersonneType">
		<xs:all> <!-- La sequence doit etre respecte ! -->
			<xs:element minOccurs="0" name="codeerreur">
				<xs:simpleType>
					<xs:restriction base="xs:int"> <!-- codé par un type simple int et -->
						<xs:enumeration value="100" /> <!-- et une enumeration -->
						<xs:enumeration value="110" />
						<xs:enumeration value="200" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:all>
		<xs:attribute name="etat" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="KO" />
					<xs:enumeration value="OK" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute type="xs:int" name="id" use="optional" />
	</xs:complexType>


	<!-- _______ Operation recherche voisins _______ -->
	<xs:element name="Voisins" type="exem:VoisinsType"
		xmlns:exem="http://www.univ-tlse3.fr/Services/Covoiturage" />

	<xs:complexType name="VoisinsType">
		<xs:sequence>
			<xs:element type="exem:PersonneEtAdresseType" name="voisin"
				minOccurs="0" maxOccurs="unbounded" xmlns:exem="http://www.univ-tlse3.fr/Services/Covoiturage" />
		</xs:sequence>
	</xs:complexType>



	<!-- ************************** TYPES COMPLEXES ************************** -->

	<xs:complexType name="PersonneEtAdresseType">
		<xs:sequence>
			<xs:element type="exem:PersonneType" name="personne" />
			<xs:element type="exem:AdresseType" name="adresse" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="PersonneType">
		<xs:sequence>
			<xs:element type="xs:string" name="nom" />
			<xs:element type="xs:string" name="prenom" />
			<xs:element name="email">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-zA-Z][a-zA-Z0-9\-\.]*@univ-tlse3.fr" />
						<!-- commence par une lettre puis éventuelement des chifres ou des 
							lettres et fini obligatoirement @univ-tlse3.fr -->
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AdresseType">
		<xs:sequence>
			<xs:element type="xs:int" name="numrue" />
			<xs:element type="xs:int" name="numpostal" />
			<xs:element type="xs:string" name="ville" />
			<xs:element type="xs:string" name="rue" />
		</xs:sequence>
	</xs:complexType>


	<!-- ************************** REQUETES ************************** -->
	<!-- _______ Ajout de membre _______ -->
	<xs:element name="AjoutRequest" type="exem:AjoutRequestType"
		xmlns:exem="http://www.univ-tlse3.fr/Services/Covoiturage" />

	<xs:complexType name="AjoutRequestType">
		<xs:sequence>
			<xs:element name="Personne" type="exem:PersonneType"
				xmlns:exem="http://www.univ-tlse3.fr/Services/Covoiturage" />
			<xs:element name="Adresse" type="exem:AdresseType"
				xmlns:exem="http://www.univ-tlse3.fr/Services/Covoiturage" />
		</xs:sequence>
	</xs:complexType>


	<!-- _______ Recherche de voisins _______ -->
	<xs:element name="VoisinsRequest" type="exem:VoisinsRequestType"
		xmlns:exem="http://www.univ-tlse3.fr/Services/Covoiturage" />

	<xs:complexType name="VoisinsRequestType">
		<xs:sequence>
			<xs:element type="xs:int" name="idUtil" />
			<xs:element type="xs:float" name="rayon" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== FlorentMouysset/IAWSProjet/Covoiturage-Spring-WS/Covoiturage-WS/src/main/resources/CovoiturageRequest_add_ok.xml
<AjoutRequest xmlns="http://www.univ-tlse3.fr/Services/Covoiturage"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.univ-tlse3.fr/Services/Covoiturage Covoiturage.xsd">
	
	<Personne>
      <nom>nom5</nom>
      <prenom>prenom5</prenom>
      <email>mail5@univ-tlse3.fr</email>
    </Personne>
    <Adresse>
      <numrue>10</numrue>
      <numpostal>31062</numpostal>
      <ville>Toulouse</ville>
      <rue>Chemin des Izards</rue>
    </Adresse>
    
	
</AjoutRequest>

=== FlorentMouysset/IAWSProjet/Covoiturage-Spring-WS-old/Covoiturage-WS/src/main/resources/CovoiturageVoisins_NonVide.xml
<Voisins xmlns="http://www.univ-tlse3.fr/Services/Covoiturage"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.univ-tlse3.fr/Services/Covoiturage Covoiturage.xsd">
	<voisin>
		<personne>
			<nom>nom0</nom>
			<prenom>prenom0</prenom>
			<email>mail0@univ-tlse3.fr</email>
		</personne>
		<adresse>
			<numrue>65</numrue>
			<numpostal>31520</numpostal>
			<ville>Ramonville-Saint-Agne</ville>
			<rue>Avenue Tolosane</rue>
		</adresse>
		</voisin>
		<voisin>
		<personne>
			<nom>nom2</nom>
			<prenom>prenom2</prenom>
			<email>mail2@univ-tlse3.fr</email>
		</personne>
		<adresse>
			<numrue>141</numrue>
			<numpostal>31062</numpostal>
			<ville>Toulouse</ville>
			<rue>Avenue de Rangueil</rue>
		</adresse>
	</voisin>
</Voisins>
