=== FlorentMouysset/IAWSProjet/Mouysset_Ould- Amer/Covoiturage-Spring-WS/Covoiturage/src/test/resources/BD_tests/bd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:bd="http://www.univ-tlse3.fr/Services/Covoiturage"
	attributeFormDefault="unqualified" elementFormDefault="qualified"
	targetNamespace="http://www.univ-tlse3.fr/Services/Covoiturage">

<!-- 	 <xs:element name="PersonnesLocalisees" type="bd:ListePersonnesType"
		xmlns:bd="http://www.univ-tlse3.fr/Services/Covoiturage"  />
 --> 

<!-- 
	<xs:complexType name="ListePersonnesType">
		<xs:all>
 -->			<xs:element name="PersonnesLocalisees">
				<xs:complexType>
					<xs:sequence>
						<xs:element type="bd:PersonneLocaliseeType" name="personnelocalisee"
							minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
<!-- 		</xs:all>
	</xs:complexType>
 -->

	<xs:complexType name="PersonneLocaliseeType">
		<xs:sequence>
			<xs:element name="Personne" type="bd:PersoneType"
				xmlns:bd="http://www.univ-tlse3.fr/Services/Covoiturage" />
			<xs:element name="Adresse" type="bd:AdresseType"
				xmlns:bd="http://www.univ-tlse3.fr/Services/Covoiturage" />
			<xs:element name="LonLat" type="bd:LatLonType"
				xmlns:bd="http://www.univ-tlse3.fr/Services/Covoiturage" />
			<xs:element name="id" type="xs:int" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="PersoneType">
		<xs:sequence>
			<xs:element type="xs:string" name="nom" />
			<xs:element type="xs:string" name="prenom" />
			<xs:element name="email">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-zA-Z][a-zA-Z0-9\-\.]*@univ-tlse3.fr" />
						<!-- commence par une lettre puis Ã©ventuelement des chifres ou des 
							lettres et fini obligatoirement @univ-tlse3.fr -->
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AdresseType">
		<xs:sequence>
			<xs:element type="xs:int" name="numrue" />
			<xs:element type="xs:int" name="numpostal" />
			<xs:element type="xs:string" name="ville" />
			<xs:element type="xs:string" name="rue" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="LatLonType">
		<xs:sequence>
			<xs:element type="xs:double" name="lat" />
			<xs:element type="xs:double" name="lon" />
		</xs:sequence>
	</xs:complexType>







</xs:schema>

=== FlorentMouysset/IAWSProjet/Covoiturage-Spring-WS/Covoiturage/src/main/resources/bd.xml
<PersonnesLocalisees xmlns="http://www.univ-tlse3.fr/Services/Covoiturage"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.univ-tlse3.fr/Services/Covoiturage bd.xsd">


	<personnelocalisee>
		<Personne>
			<nom>toto</nom>
			<prenom>dupont</prenom>
			<email>toto.dupont@univ-tlse3.fr</email>
		</Personne>
		<Adresse>
			<numrue>1</numrue>
			<numpostal>31500</numpostal>
			<ville>toulouse</ville>
			<rue>Gaillac</rue>
		</Adresse>
		<LonLat>
			<lat>1.2</lat>
			<lon>2.3</lon>
		</LonLat>
		<id>0</id>
	</personnelocalisee>

	<personnelocalisee>
		<Personne>
			<nom>toto</nom>
			<prenom>dupont</prenom>
			<email>toto.dupont@univ-tlse3.fr</email>
		</Personne>
		<Adresse>
			<numrue>1</numrue>
			<numpostal>31500</numpostal>
			<ville>toulouse</ville>
			<rue>Gaillac</rue>
		</Adresse>
		<LonLat>
			<lat>1.2</lat>
			<lon>2.3</lon>
		</LonLat>
		<id>1</id>	
	</personnelocalisee>
	
	
</PersonnesLocalisees>
