=== FlorentMouysset/IAWSProjet/Covoiturage-Spring-WS/Covoiturage-WS/src/main/java/Covoiturage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" targetNamespace="http://www.univ-tlse3.fr/Services/Covoiturage"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- ************** REPONSE *********** -->
	<!-- Operation Ajoute personne -->
	<xs:element name="Ajout" type="exem:AjoutPersoneType"
		xmlns:exem="http://www.univ-tlse3.fr/Services/Covoiturage" />

	<!-- retour de la méthode 'Ajout' : type complexe 'AjoutPersonne' -->
	<xs:complexType name="AjoutPersoneType" mixed="true">
		<xs:sequence> <!-- La sequence doit etre respecte ! -->
			<xs:element minOccurs="0" name="codeerreur">
			<xs:simpleType>
				<xs:restriction base="xs:int"> <!-- codé par un type simple int et -->
					<xs:enumeration value="100" /> <!-- et une enumeration -->
					<xs:enumeration value="110" />
					<xs:enumeration value="200" />
				</xs:restriction>
			</xs:simpleType>
			</xs:element>

		</xs:sequence>
		<xs:attribute name="etat" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"> <!-- codé par un type simple int et -->
					<xs:enumeration value="KO" /> <!-- et une enumeration -->
					<xs:enumeration value="OK" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>






	<!-- ************** TYPES COMPLEXES *********** -->
	<xs:complexType name="PersoneType">
		<xs:sequence>
			<xs:element type="xs:string" name="nom" />
			<xs:element type="xs:string" name="prenom" />

			<xs:element name="email">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-zA-Z][a-zA-Z0-9\-\.]*@univ-tlse3.fr" /> 
						<!-- commence par une lettre puis éventuelement des chifres ou 
							des lettres et fini obligatoirement @univ-tlse3.fr -->
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="AdresseType">
		<xs:sequence>
			<xs:element type="xs:int" name="numrue"  />
			<xs:element type="xs:int" name="numpostal"  />
		</xs:sequence>
	</xs:complexType>

	<!-- ************** REQUETES *********** -->
	<xs:element name="AjoutRequest" type="exem:AjoutRequestType"
		xmlns:exem="http://www.univ-tlse3.fr/Services/Covoiturage" />

	<xs:complexType name="AjoutRequestType">
		<xs:sequence>
			<xs:element name="Persone" type="exem:PersoneType"
				xmlns:exem="http://www.univ-tlse3.fr/Services/Covoiturage" />
			<xs:element name="Adresse" type="exem:AdresseType"
				xmlns:exem="http://www.univ-tlse3.fr/Services/Covoiturage" />
		</xs:sequence>
	</xs:complexType>





</xs:schema>

=== FlorentMouysset/IAWSProjet/Covoiturage-Spring-WS/Covoiturage-WS/src/main/resources/CovoiturageRequest_add_110.xml
<AjoutRequest xmlns="http://www.univ-tlse3.fr/Services/Covoiturage"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.univ-tlse3.fr/Services/Covoiturage Covoiturage.xsd">


	<Persone>
		<nom>toto</nom>
		<prenom>dupont</prenom>
		<email>existepas.alafac@univ-tlse3.fr</email>
	</Persone>
	 <Adresse>
		<numrue>1</numrue>
		<numpostal>31500</numpostal>
		<ville>toulouse</ville>
		<rue>Gaillac</rue>
	</Adresse>
	
</AjoutRequest>
